Downgrade joi to 11.4.0
/nyhedsbreve/node_modules/joi/lib/index.js:48
    root.any = function (...args) {
                         ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/nyhedsbreve/src/smartlinks.js:4:11)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)